### ISSUE TITLE
Fix regex in the challenge name parser

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/fcc-scraper#7]
Spaces are being dealt with inconsistently.

See line 5 of controllers/getSolution.js

**Comment by mrslwiseman** [comment]
Hi Jackson, Im Matt, I'm a freecodecamper from Melbourne, seen you a few times ages ago at FCC Melb. Do you mind if have a go at my first pull requests here with you? 
I'm fairly sure I've sorted this issue, the replace function is missing the first space.
line 5 of controllers/getSolution.js was removing the '%' symbol thus leaving just a '20' and the subsequent replace function in writeFile.js was ignoring that space...

I've worked out what the solution is, but am just trying to figure out best way to make a pull request, never done one before!

**Comment by JacksonBates** [comment]
Hi Matt!

You're more than welcome to have a crack at it.

I actually made a video walkthrough for pull requests last year which might help. The gist of it is to fork the repo, check out a new branch for the fix, make the change, commit the change, push the commit and then open up a pull request across branches on my original repo. Sounds complicated, but this should help:

https://www.youtube.com/watch?v=dSl_qnWO104&t=104s

When you test it - test against the camper **portablestick**. He has some older solutions that include odd characters that broke the old regex I had. Fixing that introduced the current problem, so ensure your fix doesn't undo that fix :)

Once you PR, I'll review your code and walk you through any changes they might need.

**Comment by mrslwiseman** [comment]
Thanks Jackson. I totally thought this was an open source thing and here I am crashing your lil project haha! 
Your vid is excellent by the way. If you could leave those simpler bugs to me, I'll get on to them. 
PR coming through!

**Comment by JacksonBates** [comment]
If it's on GH it's an open source thing! Always happy to have contributors :)

**Comment by JacksonBates** [comment]
fixed by #16
